# Generated by Django 4.1.6 on 2023-02-20 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfilesModel',
        ),
    ]
